language: node_js
node_js: "10"
cache:
  directories:
    - "node_modules"
matrix:
  include:
    - os: linux
      dist: bionic
      before_install:
        - sudo apt install libxss-dev -y
install:
  - npm ci --prefer-offline --no-audit
script:
  - npm run lint
  - npm run release
