name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: ubuntu packages
        run: sudo apt install libxss-dev -y
        if: matrix.platform == 'ubuntu-latest'
      - name: npm install, build, and test
        run: |
          npm ci --prefer-offline --no-audit
          npm run build --if-present
          npm run lint
        env:
          CI: true
